version: 2.1
orbs:
  android: circleci/android@3.0.2
jobs:
  build-apk:
    machine:
      image: android:2024.11.1
    steps:
      - checkout
      - run:
          name: Build APK
          command: ./gradlew assembleDebug
workflows:
  build-apk-workflow:
    jobs:
      - build-apk