version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:2023.10.1-jdk17
    working_directory: ~/repo

jobs:
  build:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -sL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
      - run:
          name: Install Dependencies
          command: |
            cd telon-gateway-app
            npm install
      - run:
          name: Build APK
          command: |
            cd telon-gateway-app/android
            ./gradlew assembleRelease

workflows:
  version: 2
  build:
    jobs:
      - build
